const recipes = [
  {
    id: 1,
    title: "Mulled Wine (Gløgg)",
    picture_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Gl%C3%B6gg_kastrull.JPG/800px-Gl%C3%B6gg_kastrull.JPG",
    description:
      "Gløgg is a traditional Scandinavian mulled wine, often enjoyed during the winter months and holiday season. This warming beverage is made by infusing red wine with spices such as cinnamon, cloves, and orange zest, then sweetened with sugar and garnished with raisins and almonds. Perfect for cozy gatherings, Gløgg offers a fragrant and festive treat that embodies the spirit of Scandinavian hospitality.",
    ingredients: [
      { NAME: "Orange zest", AMOUNT: "0.5" },
      { NAME: "Water", AMOUNT: "200 ml" },
      { NAME: "Sugar", AMOUNT: "275 g" },
      { NAME: "Whole cloves", AMOUNT: "5" },
      { NAME: "Cinnamon sticks", AMOUNT: "2" },
      { NAME: "Spice", AMOUNT: undefined },
      { NAME: "Bottle of red wine", AMOUNT: "1" },
      { NAME: "Raisins", AMOUNT: "100 g" },
      { NAME: "Slipped Almonds", AMOUNT: "50 g" },
    ],
    preparationSteps: [
      "Zest half an orange.",
      "Measure 200 ml water and 275 g sugar.",
      "Gather 5 whole cloves and 2 cinnamon sticks.",
      "Combine water, sugar, orange zest, cloves, and cinnamon sticks in a pot.",
      "Heat and stir until sugar dissolves. Simmer for 10-15 minutes.",
      "Pour in 1 bottle of red wine.",
      "Heat gently without boiling for 10-15 minutes.",
      "Add 100 g raisins and 50 g slipped almonds.",
      "Ladle into mugs and serve hot.",
    ],
    published: "Aug 13",
    likes: 30,
    comments: 18,
  },
  {
    id: 2,
    title: "Crisp Pork (Flæskesteg)",
    picture_url:
      "https://i0.wp.com/skandibaking.com/wp-content/uploads/2022/12/danish-roast-pork-flaeskesteg-5.jpg?w=1381&ssl=1",
    description:
      "Flæskesteg, a Danish Crisp Pork, is a cherished dish deeply rooted in Danish culinary tradition. It's not just a meal; it's a centerpiece of celebration, often enjoyed during holidays like Christmas. This dish boasts a succulent pork roast with a perfectly crispy and crackling skin, making it a delight for both the palate and the senses.",
    ingredients: [
      { NAME: "Pork roast with rind", AMOUNT: "1.5-2 kg" },
      { NAME: "Salt", AMOUNT: "appropriate" },
      { NAME: "Pepper", AMOUNT: "appropriate" },
      { NAME: "Bay leaves", AMOUNT: "4-5" },
      { NAME: "Water", AMOUNT: "500 ml" },
    ],
    preparationSteps: [
      "Preheat the oven to 225°C (437°F).",
      "Score the rind of the pork roast in a crisscross pattern, being careful not to cut into the meat.",
      "Rub the entire roast with a generous amount of salt, ensuring it gets into the scored rind. Season with pepper.",
      "Place bay leaves in the slits of the scored rind.",
      "Place the roast on a rack in a roasting pan. Pour 500 ml of water into the bottom of the pan.",
      "Roast in the oven for about 15 minutes at 225°C (437°F) to start the crackling process.",
      "Reduce the oven temperature to 200°C (392°F) and continue to roast for about 1.5 hours, or until the internal temperature of the meat reaches 65°C (149°F).",
      "If the rind isn't crispy enough, turn on the broiler for the last few minutes, keeping a close eye to prevent burning.",
      "Let the roast rest for 10-15 minutes before carving.",
      "Carve and serve with traditional sides like boiled potatoes, red cabbage, and gravy.",
    ],
    published: "Sep 25",
    likes: 42,
    comments: 30,
  },
  {
    id: 3,
    title: "Japanese Ramen",
    picture_url:
      "https://static.ffx.io/images/$zoom_1%2C$multiply_0.3722%2C$ratio_1.777778%2C$width_1988%2C$x_12%2C$y_164/t_crop_custom/q_86%2Cf_auto/710bea595f170be6cce26de5d3a0813173e2161a",
    description:
      "Japanese Ramen is a flavorful noodle soup with a rich broth, tender noodles, and various toppings like sliced pork, soft-boiled eggs, and green onions. It's a hearty and comforting meal.",
    ingredients: [
      { NAME: "Ramen noodles", AMOUNT: "400g" },
      { NAME: "Pork belly", AMOUNT: "500g, sliced" },
      { NAME: "Chicken broth", AMOUNT: "1.5 liters" },
      { NAME: "Soy sauce", AMOUNT: "100ml" },
      { NAME: "Mirin", AMOUNT: "50ml" },
      { NAME: "Garlic", AMOUNT: "4 cloves, minced" },
      { NAME: "Ginger", AMOUNT: "1 tbsp, grated" },
      { NAME: "Soft-boiled eggs", AMOUNT: "4" },
      { NAME: "Green onions", AMOUNT: "for garnish" },
      { NAME: "Nori (seaweed)", AMOUNT: "4 sheets" },
      { NAME: "Salt", AMOUNT: "to taste" },
    ],
    preparationSteps: [
      "In a pot, bring the chicken broth to a boil. Add the soy sauce, mirin, garlic, and ginger. Simmer for 20 minutes.",
      "Cook the ramen noodles according to package instructions. Drain and set aside.",
      "In a pan, cook the pork belly slices until crispy.",
      "Divide the noodles among four bowls. Pour the hot broth over the noodles.",
      "Top each bowl with slices of pork belly, a soft-boiled egg, chopped green onions, and a sheet of nori.",
    ],
    published: "May 10",
    likes: 89,
    comments: 45,
  },
  {
    id: 4,
    title: "French Onion Soup",
    picture_url:
      "https://assets.bonappetit.com/photos/5c634f0d050c433e0a336d6a/1:1/w_1920,c_limit/healthyish-french-onion-horizontal.jpg",
    description:
      "French Onion Soup is a classic French dish made with caramelized onions, beef broth, and topped with toasted bread and melted cheese. It's a comforting and flavorful soup perfect for cold days.",
    ingredients: [
      { NAME: "Onions", AMOUNT: "1 kg, thinly sliced" },
      { NAME: "Butter", AMOUNT: "50g" },
      { NAME: "Olive oil", AMOUNT: "2 tbsp" },
      { NAME: "Beef broth", AMOUNT: "1.5 liters" },
      { NAME: "White wine", AMOUNT: "200ml" },
      { NAME: "Thyme", AMOUNT: "1 tsp" },
      { NAME: "Bay leaf", AMOUNT: "1" },
      { NAME: "Baguette", AMOUNT: "sliced and toasted" },
      { NAME: "Gruyere cheese", AMOUNT: "200g, grated" },
      { NAME: "Salt", AMOUNT: "to taste" },
      { NAME: "Pepper", AMOUNT: "to taste" },
    ],
    preparationSteps: [
      "In a large pot, melt the butter with the olive oil over medium heat. Add the onions and cook until caramelized, about 30 minutes.",
      "Add the white wine to deglaze the pot, scraping up any browned bits from the bottom.",
      "Add the beef broth, thyme, and bay leaf. Bring to a boil, then reduce the heat and simmer for 30 minutes. Season with salt and pepper.",
      "Preheat the oven to 200°C (392°F). Ladle the soup into oven-safe bowls, place a slice of toasted baguette on top of each, and sprinkle with grated Gruyere cheese.",
      "Place the bowls in the oven and bake until the cheese is melted and bubbly.",
    ],
    published: "Feb 18",
    likes: 65,
    comments: 19,
  },
  {
    id: 5,
    title: "Chocolate Chip Cookies",
    picture_url:
      "https://joyfoodsunshine.com/wp-content/uploads/2018/02/best-chocolate-chip-cookies-recipe-1.jpg",
    description:
      "These classic chocolate chip cookies are crispy on the edges and chewy in the center, filled with gooey chocolate chunks. Perfect for a comforting treat.",
    ingredients: [
      { NAME: "Butter", AMOUNT: "1 cup, softened" },
      { NAME: "Granulated sugar", AMOUNT: "1 cup" },
      { NAME: "Brown sugar", AMOUNT: "1 cup, packed" },
      { NAME: "Eggs", AMOUNT: "2 large" },
      { NAME: "Vanilla extract", AMOUNT: "2 tsp" },
      { NAME: "All-purpose flour", AMOUNT: "3 cups" },
      { NAME: "Baking soda", AMOUNT: "1 tsp" },
      { NAME: "Salt", AMOUNT: "1/2 tsp" },
      { NAME: "Chocolate chips", AMOUNT: "2 cups" },
    ],
    preparationSteps: [
      "Preheat the oven to 175°C (350°F).",
      "In a large bowl, cream together the butter, granulated sugar, and brown sugar until light and fluffy.",
      "Beat in the eggs one at a time, then stir in the vanilla extract.",
      "Combine the flour, baking soda, and salt; gradually blend into the creamed mixture.",
      "Stir in the chocolate chips by hand using a wooden spoon.",
      "Drop cookie dough by rounded tablespoons onto ungreased cookie sheets.",
      "Bake for 10-12 minutes, or until edges are nicely browned.",
      "Allow cookies to cool on baking sheets for a few minutes before transferring to wire racks to cool completely.",
    ],
    published: "Dec 15",
    likes: 120,
    comments: 60,
  },
  {
    id: 6,
    title: "Vegetarian Sushi Rolls",
    picture_url:
      "https://www.justonecookbook.com/wp-content/uploads/2023/05/Vegetarian-Sushi-Rolls-9707-I-1.jpg",
    description:
      "These vegetarian sushi rolls are packed with fresh vegetables and seasoned rice, making them a light and healthy option for a meal or snack.",
    ingredients: [
      { NAME: "Sushi rice", AMOUNT: "2 cups" },
      { NAME: "Nori sheets", AMOUNT: "6" },
      { NAME: "Cucumber", AMOUNT: "1, julienned" },
      { NAME: "Carrot", AMOUNT: "1, julienned" },
      { NAME: "Avocado", AMOUNT: "1, sliced" },
      { NAME: "Rice vinegar", AMOUNT: "1/4 cup" },
      { NAME: "Sugar", AMOUNT: "1 tbsp" },
      { NAME: "Salt", AMOUNT: "1 tsp" },
    ],
    preparationSteps: [
      "Cook the sushi rice according to the package instructions. Once cooked, mix in the rice vinegar, sugar, and salt. Allow to cool to room temperature.",
      "Place a nori sheet on a bamboo sushi mat. Spread a thin layer of sushi rice over the nori, leaving a 1-inch border at the top.",
      "Arrange cucumber, carrot, and avocado slices in a line along the bottom edge of the rice.",
      "Using the bamboo mat, carefully roll the sushi tightly from the bottom up, pressing gently to seal.",
      "Slice the roll into 6-8 pieces with a sharp knife.",
      "Repeat with the remaining ingredients.",
      "Serve with soy sauce, pickled ginger, and wasabi.",
    ],
    published: "Jan 5",
    likes: 90,
    comments: 45,
  },
];
